name: ci
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install pytest
          pytest -q

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Banned C APIs scan
        run: |
          echo "Scanning for banned C APIs"
          MATCHES="$(rg -n -f banned_apis.txt --glob '!**/third_party/**' --glob '!**/*.md' || true)"
          if [ -n "$MATCHES" ]; then
            echo "$MATCHES"
            exit 1
          fi

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Secrets scan
        run: |
          rg -n --hidden --no-ignore -e 'BEGIN (RSA|EC|PRIVATE) KEY' -e '(password|token|secret)\s*=' -e '[A-Za-z0-9_\.-]+@[A-Za-z0-9_-]+\.[A-Za-z\.-]+' || true
          COUNT="$(rg -n --hidden --no-ignore -e 'BEGIN (RSA|EC|PRIVATE) KEY' -e '(password|token|secret)\s*=' | wc -l)"
          test "$COUNT" -eq 0

